[package]
name = "tic-tac-toe-rust"
version = "0.1.0"
authors = ["Vladislav Bargin <vladithur@mail.ru>"]
edition = "2018"

[dependencies]
text_io = "0.1.8"

[dependencies.tiny-sixel]
path = "tiny-sixel"
